### ISSUE TITLE
Ça manque de paillettes sur l'icône

### ISSUE THREAD

**Issue by cecebaltazart** [gstraymond/magic-card-search#59]
J'arrive pas bien à utiliser l'app parce que y a pas de paillettes sur l'app icon, en fait même ça l'empêche de fonctionner ça crashe à cause que y a pas de paillettes sur l'app icon.

**Comment by gstraymond** [comment]
![logo_ankormieu](https://user-images.githubusercontent.com/1651516/30312964-fdcd6b48-979b-11e7-8ec3-4aae161ebd63.png)

**Comment by gstraymond** [comment]
ET VOILA
